config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  root 'welcome#index'

  mount Sidekiq::Web, at: '/sidekiq'

  namespace :api do
    namespace :v1 do
      resources :courses, only: :index
      resource  :auth_tokens, only: :create
      resource  :auth_users, only: :create

      namespace :user do
        resources :courses, only: :index
        resource  :course_subscriptions, only: :create
      end
    end
  end

  resources :courses, only: %i[index show] do
    resources :participants, only: :index
    resource  :subscriptions, only: %i[create destroy], controller: :course_subscriptions
    resource  :feed_claims, only: %i[create destroy], controller: :course_feed_claims
    resource  :expel_participants, only: :create

    resources :lessons, only: %i[index show], controller: :course_lessons do
      resource :homeworks, only: :create, controller: :lesson_homeworks
    end
  end

  resources :lessons, controller: :course_lessons, only: [] do
    resources :comments, only: %i[create destroy]
  end

  resources :homeworks, controller: :lesson_homeworks, only: [] do
    resources :comments, only: %i[create destroy]
  end

  namespace :users do
    resource  :profile, controller: :profile
    resources :activities, only: :index

    resources :courses do
      resources :lessons do
        resources :homeworks, only: %i[index update]
      end
    end
  end

  scope 'user' do
    resources :homeworks, only: %i[index show]
  end
end

app/controllers/course_lessons_controller.rb
class CourseLessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_lesson, only: :show
  before_action :load_comments, only: :show
  before_action :if_student_is_outcast, only: %i[index show]

  PER_PAGE = 10

  def index
    @lessons = course.lessons.order_by_position.page(params[:page]).per(params[:per_page] || PER_PAGE).decorate
  end

  def show
    authorize! :manage, course
  end

  private

  def course
    @course ||= Course.find(params[:course_id])
  end
  helper_method :course

  def load_lesson
    @lesson = course.lessons.find(params[:id])
  end

  def load_comments
    @comments = @lesson.comments.includes(user: :profile)
  end

  def participant
    @participant = course.find_participant(current_user)
  end

  def if_student_is_outcast
    return unless current_user.participate_in?(course) && participant.outcast?

    redirect_to courses_path

    flash[:error] = 'You was excluded from the course'
  end
end

app/views/course_lessons/index.html.haml
#course-lessons-index
  %h1 Lessons

  - if @lessons.present?
    %table.table.table-striped{ id: 'courses-list' }
      %tr
        %th Title
        %th Start date
        %th Picture
        %th View

      - @lessons.each do |lesson|
        %tr
          %td= lesson.title
          %td= lesson.start_date
          %td= image_tag(lesson.picture.thumb)
          %td
            - if can? :manage, course
              = link_to 'View lesson', course_lesson_path(course_id: course, id: lesson), method: :get, class: 'btn btn-default'
    = paginate @lessons
  - else
    %h2 No lessons

app/views/course_lessons/show.html.haml
#course-lessons-show
  .nav-tabs-custom
    %ul.nav.nav-tabs
      %li.active
        = link_to 'Lesson', '#tab_1', 'aria-expanded': 'true', 'data-toggle': 'tab'
      %li.pull-right
        = button_to 'Deliver homework', course_lesson_homeworks_path(course, @lesson), remote: true, class: 'btn btn-default'
    .tab-content
      #tab_1.tab-pane.active
        %b Title
        %p= @lesson.title

      #tab_1.tab-pane.active
        %b Start date
        %p= @lesson.start_date

      #tab_1.tab-pane.active
        %b Descriprion
        %p= @lesson.description

      #tab_1.tab-pane.active
        %b Picture
        %p= image_tag(@lesson.picture.thumb)

      #tab_1.tab-pane.active
        %b Synopsis
        %p= @lesson.synopsis

      #tab_1.tab-pane.active
        %b Homework
        %p= @lesson.homework

  - if @comments.present?
    - @comments.each do |comment|
      .box-footer.box-comments
        .box-comment
          = image_tag(current_user.picture.thumb, alt: 'User Image', class: 'img img-circle img-sm')
          .comment-text
            - if can? :manage, comment
              = link_to lesson_comment_path(@lesson, comment), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-box-tool pull-right' do
                %i.fa.fa-times
            %span.username #{comment.user.first_name} #{comment.user.last_name}
            = comment.body

  .box-footer
    = simple_form_for [@lesson, Comment.new] do |f|
      = image_tag(current_user.picture.thumb, alt: 'Alt Text', class: 'img img-responsive img-circle img-sm')
      .img-push
        = f.input :body, as: :string, label: false, input_html: { class: 'form-control input-sm', placeholder: 'Press enter to post comment' }

#modal-lesson-homework.modal.fade{ style: 'display: none;' }