config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  root 'welcome#index'

  mount Sidekiq::Web, at: '/sidekiq'

  namespace :api do
    namespace :v1 do
      resources :courses, only: :index
      resource  :auth_tokens, only: :create
      resource  :auth_users, only: :create

      namespace :user do
        resources :courses, only: :index
        resource  :course_subscriptions, only: :create
      end
    end
  end

  resources :courses, only: %i[index show] do
    resources :participants, only: :index
    resource  :subscriptions, only: %i[create destroy], controller: :course_subscriptions
    resource  :feed_claims, only: %i[create destroy], controller: :course_feed_claims
    resource  :expel_participants, only: :create

    resources :lessons, only: %i[index show], controller: :course_lessons do
      resource :homeworks, only: :create, controller: :lesson_homeworks
    end
  end

  resources :lessons, controller: :course_lessons, only: [] do
    resources :comments, only: %i[create destroy]
  end

  resources :homeworks, controller: :lesson_homeworks, only: [] do
    resources :comments, only: %i[create destroy]
  end

  namespace :users do
    resource  :profile, controller: :profile
    resources :activities, only: :index

    resources :courses do
      resources :lessons do
        resources :homeworks, only: %i[index update]
      end
    end
  end

  scope 'user' do
    resources :homeworks, only: %i[index show]
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  include AASM

  mount_uploader :picture, LessonPictureUploader

  scope :order_by_position, -> { order(position: :asc) }

  belongs_to :course

  has_many :homeworks
  has_many :activities, as: :trackable
  has_many :comments, as: :commentable

  acts_as_list scope: :course

  validates :title, :position, :start_date, presence: true

  after_commit :send_notifications

  aasm column: :state do
    state :wait_realization, initial: true
    state :load_wait
    state :material_loaded
  end

  private

  def send_notifications
    ScheduleNewLessonNotificationWorker.perform_async(id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :picture, UserPictureUploader

  rolify

  include Omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook twitter]

  has_one  :profile
  has_many :authored_courses, class_name: 'Course', foreign_key: :user_id, dependent: :destroy
  has_many :social_profiles
  has_many :homeworks
  has_many :comments
  has_many :course_users
  has_many :participated_courses, -> { where('course_users.subscription = ?', true) }, through: :course_users, source: :course
  has_many :activities_for_me,  class_name: 'Activity', foreign_key: :recipient_id
  has_many :activities_from_me, class_name: 'Activity', foreign_key: :owner_id

  delegate :first_name, :last_name, to: :profile, allow_nil: true

  accepts_nested_attributes_for :profile

  def participate_in?(course)
    course_users.exists?(course_id: course.id)
  end

  def subscription_in?(course)
    return false unless participate_in?(course)
    course_users.where(course_id: course.id).first.subscription?
  end

  def expel_in?(course)
    course_users.where(course_id: course.id).first.outcast?
  end
end

app/controllers/api/v1/user/base_controller.rb
class Api::V1::User::BaseController < Api::V1::BaseController
  before_action :authenticate_request!
end

app/controllers/api/v1/user/course_subscriptions_controller.rb
class Api::V1::User::CourseSubscriptionsController < Api::V1::User::BaseController
  def create
    if !current_user.participate_in?(course)
      course.participants << current_user

      participant.update!(subscription: true)

      render_success 'You have successfully subscribed to the course', 201
    else
      render_error 'You have already been subscribed to the course', 403
    end
  end

  private

  def course
    @course ||= Course.find(params[:course_id])
  end

  def participant
    @participant ||= course.find_participant(current_user)
  end
end

app/controllers/api/v1/user/courses_controller.rb
class Api::V1::User::CoursesController < Api::V1::User::BaseController
  def index
    courses = current_user.participated_courses.recent

    respond_with_success(
      ActiveModel::Serializer::CollectionSerializer.new(courses, serializer: CourseWithoutAssociationsSerializer)
    )
  end
end

app/controllers/users/activities_controller.rb
class Users::ActivitiesController < Users::BaseController
  def index
    @activities = current_user.activities_for_me.includes(:trackable).recent.decorate
  end
end

app/controllers/users/base_controller.rb
class Users::BaseController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/users/courses_controller.rb
class Users::CoursesController < Users::BaseController
  before_action :find_course, only: %i[edit update destroy]
  authorize_resource only: %i[new create]

  PER_PAGE = 5

  def index
    @courses = current_user.authored_courses.recent.page(params[:page]).per(params[:per_page] || PER_PAGE).decorate
  end

  def new
    @course = current_user.authored_courses.build
  end

  def create
    @course = current_user.authored_courses.build(course_params)

    if @course.save
      redirect_to users_courses_path
      flash[:success] = 'Course was successfully created.'
    else
      render :new
    end
  end

  def update
    if @course.update(course_params)
      redirect_to users_courses_path
      flash[:success] = 'Course was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @course.destroy!

    redirect_to users_courses_path
  end

  private

  def find_course
    @course = current_user.authored_courses.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :picture, :active)
  end
end

app/controllers/users/homeworks_controller.rb
class Users::HomeworksController < Users::BaseController
  before_action :load_homework, only: :update

  PER_PAGE = 10

  STATES = %w[approved rejected].freeze

  def index
    @homeworks = lesson.homeworks.includes(user: :profile).recent.page(params[:page]).per(params[:per_page] || PER_PAGE)
  end

  def update
    if STATES.include?(params[:state])
      if params[:state] == 'approved'
        @homework.approve!
      else
        @homework.reject!
      end

      send_homework_to_activities
    else
      flash[:error] = "You can't set #{params[:state]} state"
    end
  end

  private

  def course
    @course ||= current_user.authored_courses.find_by(id: params[:course_id])
  end
  helper_method :course

  def lesson
    @lesson ||= course.lessons.find_by(id: params[:lesson_id])
  end
  helper_method :lesson

  def load_homework
    @homework ||= lesson.homeworks.find(params[:id])
  end

  def send_homework_to_activities
    state =
      if params[:state] == 'approved'
        Activity::KIND_HOMEWORK_APPROVED
      else
        Activity::KIND_HOMEWORK_REJECTED
      end

    Activity.create!(
      recipient_id: @homework.user_id,
      owner_id: current_user.id,
      trackable: @homework,
      kind: state,
      message: "Homework has been #{state}"
    )
  end
end

app/controllers/users/lessons_controller.rb
class Users::LessonsController < Users::BaseController
  before_action :find_lesson, only: %i[show edit update destroy]

  PER_PAGE = 10

  def index
    @lessons = course.lessons.order_by_position.page(params[:page]).per(params[:per_page] || PER_PAGE).decorate
  end

  def new
    @lesson = course.lessons.build
  end

  def create
    @lesson = course.lessons.build(lesson_params)

    if @lesson.save
      redirect_to users_course_lessons_path(course)

      flash[:success] = 'Lesson was successfully created.'
    else
      render :new
    end
  end

  def update
    if @lesson.update(lesson_params)
      redirect_to users_course_lessons_path(course)

      flash[:success] = 'Lesson was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @lesson.destroy!

    redirect_to users_course_lessons_path(course)
  end

  private

  def find_lesson
    @lesson = course.lessons.find(params[:id]).decorate
  end

  def course
    @course ||= current_user.authored_courses.find(params[:course_id])
  end
  helper_method :course

  def lesson_params
    params.require(:lesson).permit(:title, :position, :description, :picture, :synopsis, :homework, :start_date)
  end
end

app/controllers/users/profile_controller.rb
class Users::ProfileController < Users::BaseController
  def show
    @courses = current_user.participated_courses.recent
    @activities = current_user.activities_for_me.includes(:trackable, owner: :profile).recent.decorate
  end

  def update
    if current_user.update(profile_params)
      redirect_to users_profile_path
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(
      :email, :picture, :password, :password_confirmation,
      profile_attributes: %i[id first_name last_name]
    )
  end
end

app/views/users/lessons/_form.html.haml
= simple_form_for [:users, course, lesson] do |f|
  .box-body
    .form-group
      %br
      %label Title
      = f.input :title, label: false, placeholder: 'Enter title', input_html: { class: 'form-control' }
      %label Position
      = f.input :position, collection: 1..course.lesson_positions, label: false, placeholder: 'Enter title', input_html: { class: 'form-control' }
      %label Start date
      = f.input :start_date, as: :string, label: false, html5: true, input_html: { class: 'form-control', id: 'lesson_new_start_date' }
      %label Descriprion
      = f.input :description, as: :text, label: false, placeholder: 'Enter title', input_html: { class: 'form-control' }
      %label Synopsis
      = f.input :synopsis, as: :text, label: false, placeholder: 'Enter title', input_html: { class: 'form-control' }
      %label Homework
      = f.input :homework, as: :text, label: false, placeholder: 'Enter title', input_html: { class: 'form-control' }
    .form-group
      %label{for: 'exampleInputFile'} Picture
      = f.file_field :picture, id: 'exampleInputFile'
  .box-footer
    = f.button :submit, class: 'btn btn-primary'

app/views/users/lessons/edit.html.haml
.box.box-primary
  .box-header.with-border
    %h3.box-title Edit lesson
  = render 'form', lesson: @lesson

app/views/users/lessons/index.html.haml
#course-lesson-index
  = content_for :h1_for_wrap do
    %h1.pull-left Lessons
    = link_to 'Add Lesson', new_users_course_lesson_path(course), method: :get, class: 'btn btn-default pull-right'

  - if @lessons.present?
    %table.table.table-striped
      %tr
        %th Title
        %th Position
        %th Start date
        %th Picture
        %th Homeworks of students
        %th Edit
        %th Delete

      - @lessons.each do |lesson|
        %tr
          %td
            = link_to users_course_lesson_path(course, lesson) do
              = lesson.title
          %td= lesson.position
          %td= lesson.start_date
          %td= image_tag(lesson.picture.thumb)
          %td= link_to 'Homeworks', users_course_lesson_homeworks_path(course_id: course, lesson_id: lesson), method: :get, class: 'btn btn-default'
          %td= link_to 'edit', edit_users_course_lesson_path(course_id: course, id: lesson), method: :get, class: 'btn btn-default'
          %td= link_to 'delete', users_course_lesson_path(course, lesson), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default'
    = paginate @lessons
  - else
    %h2 No lessons

app/views/users/lessons/new.html.haml
.box.box-primary
  .box-header.with-border
    %h3.box-title New lesson
  = render 'form', lesson: @lesson

app/views/users/lessons/show.html.haml
#users-lessons-show
  .nav-tabs-custom
    %ul.nav.nav-tabs
      %li.active
        = link_to 'Course', '#tab_1', 'aria-expanded': 'true', 'data-toggle': 'tab'

    .tab-content
      #tab_1.tab-pane.active
        %b Title
        %p= @lesson.title

      #tab_1.tab-pane.active
        %b Start date
        %p= @lesson.start_date

      #tab_1.tab-pane.active
        %b Description
        %p= @lesson.description

      #tab_1.tab-pane.active
        %b Picture
        %p= image_tag(@lesson.picture.thumb)

      #tab_1.tab-pane.active
        %b Synopsis
        %p= @lesson.synopsis

      #tab_1.tab-pane.active
        %b Homework
        %p= @lesson.homework