config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  root 'welcome#index'

  mount Sidekiq::Web, at: '/sidekiq'

  namespace :api do
    namespace :v1 do
      resources :courses, only: :index
      resource  :auth_tokens, only: :create
      resource  :auth_users, only: :create

      namespace :user do
        resources :courses, only: :index
        resource  :course_subscriptions, only: :create
      end
    end
  end

  resources :courses, only: %i[index show] do
    resources :participants, only: :index
    resource  :subscriptions, only: %i[create destroy], controller: :course_subscriptions
    resource  :feed_claims, only: %i[create destroy], controller: :course_feed_claims
    resource  :expel_participants, only: :create

    resources :lessons, only: %i[index show], controller: :course_lessons do
      resource :homeworks, only: :create, controller: :lesson_homeworks
    end
  end

  resources :lessons, controller: :course_lessons, only: [] do
    resources :comments, only: %i[create destroy]
  end

  resources :homeworks, controller: :lesson_homeworks, only: [] do
    resources :comments, only: %i[create destroy]
  end

  namespace :users do
    resource  :profile, controller: :profile
    resources :activities, only: :index

    resources :courses do
      resources :lessons do
        resources :homeworks, only: %i[index update]
      end
    end
  end

  scope 'user' do
    resources :homeworks, only: %i[index show]
  end
end

app/controllers/api/v1/courses_controller.rb
class Api::V1::CoursesController < Api::V1::BaseController
  def index
    courses = Course.recent

    respond_with_success courses
  end
end

app/controllers/api/v1/user/courses_controller.rb
class Api::V1::User::CoursesController < Api::V1::User::BaseController
  def index
    courses = current_user.participated_courses.recent

    respond_with_success(
      ActiveModel::Serializer::CollectionSerializer.new(courses, serializer: CourseWithoutAssociationsSerializer)
    )
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!

  PER_PAGE = 5

  def index
    @courses = Course.visible.recent.page(params[:page]).per(params[:per_page] || PER_PAGE)
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/users/courses_controller.rb
class Users::CoursesController < Users::BaseController
  before_action :find_course, only: %i[edit update destroy]
  authorize_resource only: %i[new create]

  PER_PAGE = 5

  def index
    @courses = current_user.authored_courses.recent.page(params[:page]).per(params[:per_page] || PER_PAGE).decorate
  end

  def new
    @course = current_user.authored_courses.build
  end

  def create
    @course = current_user.authored_courses.build(course_params)

    if @course.save
      redirect_to users_courses_path
      flash[:success] = 'Course was successfully created.'
    else
      render :new
    end
  end

  def update
    if @course.update(course_params)
      redirect_to users_courses_path
      flash[:success] = 'Course was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @course.destroy!

    redirect_to users_courses_path
  end

  private

  def find_course
    @course = current_user.authored_courses.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :picture, :active)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.haml
%tr{ id: "course-subscription-#{course.id}" }
  %td
    = link_to course_path(course.id), method: :get do
      = course.title
  %td= image_tag(course.picture.thumb)
  %td
    - if course.user_id != current_user.id
      = link_to 'Add subscription', course_subscriptions_path(course), method: :post, remote: true, class: 'btn btn-default course-subscription-button', style: ('display: none' if current_user.subscription_in?(course))
      = link_to 'Unsubscription', course_subscriptions_path(course), method: :delete, remote: true, class: 'btn btn-default course-unsubscribe-button', style: ('display: none' unless current_user.subscription_in?(course))
  %td= link_to 'Participants', course_participants_path(course), method: :get, class: 'btn btn-default'
  %td= link_to 'Lessons', course_lessons_path(course), method: :get, class: 'btn btn-default'

app/views/courses/_modal_user_email.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{'aria-label': 'Close', 'data-dismiss': 'modal', type: 'button'}
        %span{'aria-hidden': 'true'} ×
      %h4.modal-title You should add email for continue
    .modal-body
      = simple_form_for current_user, url: course_subscriptions_path, method: :post, html: { id: 'modal_user_email_form' } do |f|
        .box-body
          .form-group
            %br
            %label Email
            = f.input :email, label: false, placeholder: 'Enter email', input_html: { class: 'form-control' }
    .modal-footer
      %button.btn.btn-default.pull-left{'data-dismiss': 'modal', type: 'button'} Close
      %button.btn.btn-primary{type: 'submit', form: 'modal_user_email_form'} Save changes

app/views/courses/index.html.haml
#courses-index
  %h1 Courses

  - if @courses.present?
    %table.table.table-striped{ id: 'courses-list' }
      %tr
        %th Title
        %th Picture
        %th Action
        %th Lessons
        %th Participants

      - @courses.each do |course|
        = render 'courses/course', course: course

    = paginate @courses
  - else
    %h2 No Courses

#modal-missing-email.modal.fade{ style: 'display: none;' }

app/views/courses/show.html.haml
#course-show
  .nav-tabs-custom
    %ul.nav.nav-tabs
      %li.active
        = link_to 'Course', '#tab_1', 'aria-expanded': 'true', 'data-toggle': 'tab'
      %li.pull-right
        = link_to 'Participants', course_participants_path(@course), method: :get, class: 'btn btn-default', id: 'participants_button'
        = link_to 'Lessons', course_lessons_path(@course), method: :get, class: 'btn btn-default', id: 'lessons_button'
    .tab-content
      #tab_1.tab-pane.active
        %b Title
        %p= @course.title

      #tab_1.tab-pane.active
        %b Picture
        %p= image_tag(@course.picture.thumb)