config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks' }

  root 'welcome#index'

  mount Sidekiq::Web, at: '/sidekiq'

  namespace :api do
    namespace :v1 do
      resources :courses, only: :index
      resource  :auth_tokens, only: :create
      resource  :auth_users, only: :create

      namespace :user do
        resources :courses, only: :index
        resource  :course_subscriptions, only: :create
      end
    end
  end

  resources :courses, only: %i[index show] do
    resources :participants, only: :index
    resource  :subscriptions, only: %i[create destroy], controller: :course_subscriptions
    resource  :feed_claims, only: %i[create destroy], controller: :course_feed_claims
    resource  :expel_participants, only: :create

    resources :lessons, only: %i[index show], controller: :course_lessons do
      resource :homeworks, only: :create, controller: :lesson_homeworks
    end
  end

  resources :lessons, controller: :course_lessons, only: [] do
    resources :comments, only: %i[create destroy]
  end

  resources :homeworks, controller: :lesson_homeworks, only: [] do
    resources :comments, only: %i[create destroy]
  end

  namespace :users do
    resource  :profile, controller: :profile
    resources :activities, only: :index

    resources :courses do
      resources :lessons do
        resources :homeworks, only: %i[index update]
      end
    end
  end

  scope 'user' do
    resources :homeworks, only: %i[index show]
  end
end

app/views/layouts/partials/_flash_messages.html.haml
.flash-error
  - flash.each do |type, message|
    - if type == 'success'
      %div{style: 'padding: 20px 30px; background: rgb(112, 219, 112); z-index: 999999; font-size: 16px; font-weight: 600;'}
        %p{style: 'color: rgba(255, 255, 255, 0.9); display: inline-block; margin: 0px; text-decoration: none;' }
          = message
    - elsif type == 'error'
      %div{style: 'padding: 20px 30px; background: rgb(255, 26, 26); z-index: 999999; font-size: 16px; font-weight: 600;'}
        %p{style: 'color: rgba(255, 255, 255, 0.9); display: inline-block; margin: 0px; text-decoration: none;' }
          = message
    - else
      %div{style: 'padding: 20px 30px; background-color: #d9edf7; z-index: 999999; font-size: 16px; font-weight: 600;'}
        %p{style: 'color: #31708f; display: inline-block; margin: 0px; text-decoration: none;' }
          = message

app/views/layouts/partials/_footer.html.haml
%footer.main-footer
  .pull-right.hidden-xs
    %b Version
    0.0.1
  %strong
    Copyright © 2017
  All rights
  reserved.

app/views/layouts/partials/_header.html.haml
%header.main-header
  = link_to root_path, method: :get, class: 'logo' do
    %span.logo-mini
      %b> OC
    %span.logo-lg
      %b> Online courses
  %nav.navbar.navbar-static-top
    %a.sidebar-toggle{'data-toggle': 'push-menu', href: '#', role: 'button'}
      %span.sr-only Toggle navigation
    .navbar-custom-menu
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li.dropdown.user.user-menu
            %a.dropdown-toggle{'data-toggle': 'dropdown', href: '#'}
              = image_tag current_user.picture.thumb, class: 'user-image', alt: 'User Image'
              %span.hidden-xs
                = current_user.first_name
                = current_user&.last_name
            %ul.dropdown-menu
              %li.user-header
                = image_tag current_user.picture.thumb, class: 'img-circle', alt: 'User Image'
                %p
                  = current_user.first_name
                  = current_user&.last_name
                  %small Member since #{current_user.created_at.strftime("%b. %Y")}
              %li.user-footer
                .pull-left
                  = link_to 'Profile', users_profile_path, method: :get, class: 'btn btn-default btn-flat'
                .pull-right
                  = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat'
        - else
          %li
            = link_to 'Sign in', new_user_session_path
          %li
            = link_to 'Sign up', new_user_registration_path

app/views/layouts/partials/_sidebar.html.haml
%aside.main-sidebar
  %section.sidebar
    - if user_signed_in?
      .user-panel
        .pull-left.image
          = image_tag current_user.picture.thumb, class: 'img-circle', alt: 'User Imag'
        .pull-left.info
          %p
            = current_user.first_name
            = current_user&.last_name
          = link_to '#' do
            %i.fa.fa-circle.text-success
            Online
      %ul.sidebar-menu{'data-widget': 'tree'}
        %li.header MAIN NAVIGATION
        %li.active.treeview
          = link_to root_path, method: :get do
            %i.fa.fa-dashboard
            %span Dashboard
        %li.treeview
          = link_to courses_path, method: :get do
            %i.fa.fa-files-o
            %span Courses
        %li.treeview
          = link_to users_courses_path, method: :get do
            %i.fa.fa-files-o
            %span My courses
        %li.treeview
          = link_to homeworks_path, method: :get do
            %i.fa.fa-files-o
            %span My homeworks